spring:
  datasource:
    url: jdbc:h2:file:./h2db/testdb;MODE=MySQL;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true        # 브라우저에서 H2 콘솔 접근 허용
      path: /h2-console    # 접근 경로: http://localhost:8080/h2-console

  jpa:
    hibernate:
      ddl-auto: create     # 앱 시작 시 테이블 자동 생성
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: always         # data.sql 자동 실행

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

jwt:
  secret:
    key: ${JWT_SECRET_KEY}